language: python

python:
  - "3.5"

install:
  - sudo apt-get install libpq-dev python3-dev
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
