# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Imagem', 'verbose_name_plural': 'Galeria de imagens'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='favorite',
            field=models.BooleanField(default=1, help_text='Escolher a foto principal da galeria para colocar como destaque na página principal', verbose_name='Favorita'),
            preserve_default=False,
        ),
    ]
