# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170216_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='favorite',
        ),
        migrations.AddField(
            model_name='gallery',
            name='recent_picture',
            field=models.BooleanField(default=False, verbose_name='Favorita'),
        ),
    ]
