# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170216_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='link',
            field=models.URLField(blank=True, help_text='Link para o Google Driver', verbose_name='Google Driver'),
        ),
    ]
