# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0008_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('recent_picture', models.BooleanField(default=False, verbose_name='Imagem mais recente')),
                ('image', models.CharField(max_length=250, verbose_name='Url da imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Galeria de imagens',
                'verbose_name': 'Imagem',
                'ordering': ['-created_at'],
            },
        ),
    ]
