# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=250, verbose_name='Url da imagem')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Galeria de imagens', 'verbose_name_plural': 'Galerias de imagens'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='recent_picture',
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='gallery.Image'),
            preserve_default=False,
        ),
    ]
