# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20170804_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='background',
            field=models.CharField(default='', max_length=100, verbose_name='URL da imagem da pasta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título da pasta'),
        ),
    ]
