# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_gallery_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=250, verbose_name='Url da imagem')),
            ],
            options={
                'verbose_name': 'Imagens da Home',
                'verbose_name_plural': 'Imagens da Home',
            },
        ),
    ]
