# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_homeimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeimages',
            options={'verbose_name': 'Imagens da página principal', 'verbose_name_plural': 'Imagens da página principal'},
        ),
        migrations.AddField(
            model_name='homeimages',
            name='title',
            field=models.CharField(default='clara', max_length=100, verbose_name='Título da imagem'),
            preserve_default=False,
        ),
    ]
