# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_teacher',
            field=models.BooleanField(default=True, verbose_name='É a professora?'),
            preserve_default=False,
        ),
    ]
