# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Só marque para uma única pessoa', verbose_name='É a professora?'),
        ),
    ]
