# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20170219_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(max_length=100000, verbose_name='Descrição'),
        ),
    ]
