# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0005_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('photo', models.CharField(max_length=250, verbose_name='Url da imagem')),
                ('is_teacher', models.BooleanField(default=False, help_text='Só marque para uma única pessoa', verbose_name='É a professora?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Time',
                'ordering': ['-name'],
            },
        ),
    ]
