# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Time', 'verbose_name_plural': 'Time'},
        ),
    ]
