# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 00:58
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_information_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
