# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_file_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/information', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(default=1, upload_to='documents/information', verbose_name='Documentos'),
            preserve_default=False,
        ),
    ]
