# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20170219_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='link',
            field=models.URLField(blank=True, help_text='Link para o Google Driver', verbose_name='Google Driver'),
        ),
    ]
