# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_auto_20170219_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='content',
            field=models.TextField(max_length=100000, verbose_name='Conteúdo'),
        ),
    ]
