# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_auto_20170523_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='image',
        ),
    ]
