# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=180, verbose_name='Título')),
                ('description', models.TextField(max_length=550, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Sobre',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.TextField(max_length=550, verbose_name='Rodapé')),
            ],
            options={
                'verbose_name': 'Rodapé',
            },
        ),
    ]
