# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20170211_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Informações Adicionais',
                'verbose_name_plural': 'Informações Adicionais',
                'ordering': ['created_at'],
            },
        ),
    ]
