# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adicional_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adicional_Information',
            new_name='AdicionalInformation',
        ),
    ]
